version: '3.9'

services:

  guacd:
    #if linux OS is not compatible with regular guacd image: lscr.io/linuxserver/guacd
    image: guacamole/guacd
    container_name: guacd
    restart: always
    ports:
      - '4822:4822/tcp'
    networks:
      guacnetwork:

  guacamolesharp:
    container_name: guacamolesharp
    image: manuelexpunged/guacamolesharp:2.0.0
    depends_on:
      guacd:
        condition: service_started
    restart: always
    environment:
      - GuacamoleSharp:Password=YourTokenEncryptionPasswordHere
      - Guacd:Hostname=guacd
      - Guacd:Port=4822
    ports:
      - '80:80/tcp'
      - '8080:8080/tcp'
    networks:
      guacnetwork:

networks:
  guacnetwork:
    driver: bridge