version: '3.9'

services:

  guacd:
    #For Linux: image: lscr.io/linuxserver/guacd
    image: guacamole/guacd
    container_name: guacd
    restart: always
    ports:
      - '4822:4822/tcp'
    networks:
      guacnetwork:

  guacamolesharp:
    container_name: guacamolesharp
    image: guacamolesharp
    build:
      context: .
    depends_on:
      guacd:
        condition: service_started
    restart: always
    ports:
      - '80:80/tcp'
      - '8080:8080/tcp'
    networks:
      guacnetwork:

networks:
  guacnetwork:
    driver: bridge